// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-escolas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-escolas.ts
var list_escolas_default = defineTool({
  name: "list_escolas",
  title: "Listar escolas",
  description: "Lista as escolas da rede vis\xEDveis para o usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("escolas").select("id, nome, saesc, tipo, regiao, localidade, ativa").order("nome").limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { escolas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-turmas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.1.12";
var list_turmas_default = defineTool2({
  name: "list_turmas",
  title: "Listar turmas",
  description: "Lista as turmas de uma escola (por id da escola), opcionalmente filtrando por turno.",
  inputSchema: {
    escola_id: z.string().describe("UUID da escola."),
    turno: z.string().optional().describe("Turno da turma, ex: MATUTINO, VESPERTINO, INTEGRAL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ escola_id, turno }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("turmas").select("id, turma, grupo_ano, etapa_modalidade, turno, ativa, escola_id").eq("escola_id", escola_id).order("turma").limit(300);
    if (turno) query = query.eq("turno", turno);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { turmas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-alunos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.1.12";
var list_alunos_default = defineTool3({
  name: "list_alunos",
  title: "Listar alunos da turma",
  description: "Lista os alunos matriculados em uma turma pelo id da turma.",
  inputSchema: {
    turma_id: z2.string().describe("UUID da turma.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ turma_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("alunos").select("id, nomalu, numalu, nummtr, sigtur, ativo, turma_id").eq("turma_id", turma_id).order("nomalu").limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { alunos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-horario-turma.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.1.12";
var get_horario_turma_default = defineTool4({
  name: "get_horario_turma",
  title: "Consultar hor\xE1rio da turma",
  description: "Retorna a grade de hor\xE1rios (dia, tempo, componente, professor) de uma turma.",
  inputSchema: {
    turma_id: z3.string().describe("UUID da turma.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ turma_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("horarios").select("id, turma_id, dia_semana, tempo, componente_curricular, professor_id").eq("turma_id", turma_id).order("dia_semana").order("tempo").limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { horarios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lotacoes-escola.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.1.12";
var list_lotacoes_escola_default = defineTool5({
  name: "list_lotacoes_escola",
  title: "Listar lota\xE7\xF5es da escola",
  description: "Lista as lota\xE7\xF5es ativas (professores e gestores) de uma escola pelo c\xF3digo SAESC.",
  inputSchema: {
    escola_saesc: z4.string().describe("C\xF3digo SAESC da escola.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ escola_saesc }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lotacoes").select("id, pessoa_id, perfil, carga_horaria, carga_total, pl, ano_letivo, status, ativo, escola_saesc").eq("escola_saesc", escola_saesc).eq("ativo", true).limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lotacoes: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tephygczbkacwdxpjqvv";
var mcp_default = defineMcp({
  name: "avaliamais",
  title: "avaliamais",
  version: "0.1.0",
  instructions: "Ferramentas de leitura do Avalia+ (gest\xE3o escolar da REME). Use list_escolas para localizar uma escola, list_turmas para suas turmas, list_alunos para os alunos de uma turma, get_horario_turma para a grade hor\xE1ria e list_lotacoes_escola para as lota\xE7\xF5es ativas. Todos os dados respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_escolas_default, list_turmas_default, list_alunos_default, get_horario_turma_default, list_lotacoes_escola_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
